// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnlecprwsxtkefufuvui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNubGVjcHJ3c3h0a2VmdWZ1dnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDIyMTgsImV4cCI6MjA3MTQ3ODIxOH0.DmvpNI5JcRM0wnHPvU_aLN2t8J3IdMkTtgBzkfzJU7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});